-- Popolare il database con profili demo
INSERT INTO public.profiles (
  id, name, username, bio, mood, job_title, relationship_status,
  interests, avatar_url, personality_type, chat_permission, privacy_level,
  is_verified, instagram_username
) VALUES
(
  'a1b2c3d4-e5f6-4789-9abc-def123456789',
  'Marco Rossi',
  'marco_explorer', 
  'Fotografo di viaggio 📸 Amo esplorare nuovi posti e condividere momenti autentici. Sempre in cerca della luce perfetta!',
  'Avventuroso',
  'Fotografo',
  'Single',
  ARRAY['fotografia', 'viaggi', 'natura', 'trekking', 'sunset'],
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face',
  'ENFP',
  'everyone',
  'public',
  true,
  'marco_explorer'
),
(
  'b2c3d4e5-f6g7-5890-0bcd-ef1234567890',
  'Sofia Chen',
  'sofia_design',
  'UX Designer & Coffee enthusiast ☕ Creo esperienze digitali che connettono le persone. Milano è casa ma il mondo è la mia palestra!',
  'Creativa',
  'UX Designer',
  'In una relazione',
  ARRAY['design', 'caffè', 'arte', 'musei', 'architettura'],
  'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=300&h=300&fit=crop&crop=face',
  'INTJ',
  'friends_only',
  'public',
  false,
  'sofia_design'
),
(
  'c3d4e5f6-g7h8-6901-1cde-f12345678901',
  'Alessandro Verde',
  'alex_music',
  'Musicista indie 🎸 Suono nei locali di Roma e organizzo jam session. La musica è il linguaggio universale dell"anima!',
  'Melodico',
  'Musicista',
  'Single',
  ARRAY['musica', 'concerti', 'chitarra', 'indie', 'jazz'],
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&crop=face',
  'ISFP',
  'followers_only',
  'public',
  true,
  'alex_music'
),
(
  'd4e5f6g7-h8i9-7012-2def-123456789012',
  'Giulia Bianchi',
  'giulia_fit',
  'Personal trainer & Nutrizionista 💪 Ti aiuto a raggiungere i tuoi obiettivi fitness! Mente sana in corpo sano è il mio motto.',
  'Energica',
  'Personal Trainer',
  'Single',
  ARRAY['fitness', 'nutrizione', 'yoga', 'running', 'wellness'],
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop&crop=face',
  'ESTJ',
  'everyone',
  'public',
  false,
  'giulia_fit'
),
(
  'e5f6g7h8-i9j0-8123-3efg-234567890123',
  'Luca Marinelli',
  'luca_chef',
  'Chef appassionato 👨‍🍳 Cucina tradizionale italiana con un twist moderno. Credo che ogni piatto racconti una storia!',
  'Gustoso',
  'Chef',
  'Fidanzato',
  ARRAY['cucina', 'vino', 'tradizione', 'innovazione', 'degustazioni'],
  'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop&crop=face',
  'ESFJ',
  'friends_only',
  'public',
  true,
  'luca_chef'
),
(
  'f6g7h8i9-j0k1-9234-4fgh-345678901234',
  'Martina Russo',
  'marti_books',
  'Libraia & Scrittrice 📚 Gestisco una piccola libreria nel centro storico. Ogni libro è un mondo da scoprire insieme!',
  'Riflessiva',
  'Libraia',
  'Single',
  ARRAY['lettura', 'scrittura', 'caffè', 'poesia', 'letteratura'],
  'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop&crop=face',
  'INFP',
  'friends_only',
  'friends_only',
  false,
  'marti_books'
),
(
  'g7h8i9j0-k1l2-0345-5ghi-456789012345',
  'Davide Conti',
  'dave_tech',
  'Full-stack developer 💻 Lavoro in remoto e amo il digital nomadismo. Codice pulito e caffè forte sono le mie passioni!',
  'Concentrato',
  'Developer',
  'Single', 
  ARRAY['programmazione', 'tecnologia', 'startup', 'gaming', 'innovazione'],
  'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&fit=crop&crop=face',
  'INTP',
  'everyone',
  'public',
  false,
  'dave_tech'
),
(
  'h8i9j0k1-l2m3-1456-6hij-567890123456',
  'Francesca Neri',
  'franci_yoga',
  'Istruttrice di Yoga & Meditazione 🧘‍♀️ Aiuto le persone a trovare equilibrio e pace interiore. Namaste!',
  'Zen',
  'Istruttrice Yoga',
  'In una relazione',
  ARRAY['yoga', 'meditazione', 'mindfulness', 'natura', 'spiritualità'],
  'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&h=300&fit=crop&crop=face',
  'INFJ',
  'followers_only',
  'public',
  true,
  'franci_yoga'
),
(
  'i9j0k1l2-m3n4-2567-7ijk-678901234567',
  'Roberto Lombardi',
  'rob_adventure',
  'Guida escursionistica ⛰️ Conosco ogni sentiero delle Dolomiti! Condivido la bellezza della montagna con chi ama l"avventura.',
  'Selvaggio',
  'Guida Escursionistica',
  'Sposato',
  ARRAY['montagna', 'escursioni', 'alpinismo', 'natura', 'fotografia'],
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face',
  'ISTP',
  'friends_only',
  'public',
  false,
  'rob_adventure'
),
(
  'j0k1l2m3-n4o5-3678-8jkl-789012345678',
  'Valentina Galli',
  'vale_art',
  'Artista contemporanea 🎨 Dipingo emozioni su tela. L"arte è il mio modo di comunicare con il mondo e toccare le anime!',
  'Ispirata',
  'Artista',
  'Single',
  ARRAY['arte', 'pittura', 'gallerie', 'creatività', 'espressionismo'],
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face',
  'ENFJ',
  'everyone',
  'public',
  true,
  'vale_art'
);