-- Popolare il database con profili demo usando gen_random_uuid()
INSERT INTO public.profiles (
  id, name, username, bio, mood, job_title, relationship_status,
  interests, avatar_url, personality_type, chat_permission, privacy_level,
  is_verified, instagram_username
) VALUES
(
  gen_random_uuid(),
  'Marco Rossi',
  'marco_explorer', 
  'Fotografo di viaggio 📸 Amo esplorare nuovi posti e condividere momenti autentici. Sempre in cerca della luce perfetta!',
  'Avventuroso',
  'Fotografo',
  'Single',
  ARRAY['fotografia', 'viaggi', 'natura', 'trekking', 'sunset'],
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face',
  'ENFP',
  'everyone',
  'public',
  true,
  'marco_explorer'
),
(
  gen_random_uuid(),
  'Sofia Chen',
  'sofia_design',
  'UX Designer & Coffee enthusiast ☕ Creo esperienze digitali che connettono le persone. Milano è casa ma il mondo è la mia palestra!',
  'Creativa',
  'UX Designer',
  'In una relazione',
  ARRAY['design', 'caffè', 'arte', 'musei', 'architettura'],
  'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=300&h=300&fit=crop&crop=face',
  'INTJ',
  'friends_only',
  'public',
  false,
  'sofia_design'
),
(
  gen_random_uuid(),
  'Alessandro Verde',
  'alex_music',
  'Musicista indie 🎸 Suono nei locali di Roma e organizzo jam session. La musica è il linguaggio universale dell''anima!',
  'Melodico',
  'Musicista',
  'Single',
  ARRAY['musica', 'concerti', 'chitarra', 'indie', 'jazz'],
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&crop=face',
  'ISFP',
  'followers_only',
  'public',
  true,
  'alex_music'
),
(
  gen_random_uuid(),
  'Giulia Bianchi',
  'giulia_fit',
  'Personal trainer & Nutrizionista 💪 Ti aiuto a raggiungere i tuoi obiettivi fitness! Mente sana in corpo sano è il mio motto.',
  'Energica',
  'Personal Trainer',
  'Single',
  ARRAY['fitness', 'nutrizione', 'yoga', 'running', 'wellness'],
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop&crop=face',
  'ESTJ',
  'everyone',
  'public',
  false,
  'giulia_fit'
),
(
  gen_random_uuid(),
  'Luca Marinelli',
  'luca_chef',
  'Chef appassionato 👨‍🍳 Cucina tradizionale italiana con un twist moderno. Credo che ogni piatto racconti una storia!',
  'Gustoso',
  'Chef',
  'Fidanzato',
  ARRAY['cucina', 'vino', 'tradizione', 'innovazione', 'degustazioni'],
  'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop&crop=face',
  'ESFJ',
  'friends_only',
  'public',
  true,
  'luca_chef'
),
(
  gen_random_uuid(),
  'Valentina Galli',
  'vale_art',
  'Artista contemporanea 🎨 Dipingo emozioni su tela. L''arte è il mio modo di comunicare con il mondo e toccare le anime!',
  'Ispirata',
  'Artista',
  'Single',
  ARRAY['arte', 'pittura', 'gallerie', 'creatività', 'espressionismo'],
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face',
  'ENFJ',
  'everyone',
  'public',
  true,
  'vale_art'
);