// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzivdgnqcyfxgmqaolux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6aXZkZ25xY3lmeGdtcWFvbHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTI5NzMsImV4cCI6MjA3MDQ2ODk3M30.q36YbhwENyiBnVT-vC17PY0MmJssYDs7e5r90bLlUkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});